### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by xuhao8948** [M-CreativeLab/template-for-jsar-widget#1]
win10系统，node版本 18.6.0，vscode拓展也装了，依赖也装了，然后点击右上角Show Scene View，vscode右下角提示command 'transmute-devtools.showSceneView' not found
![image](https://github.com/M-CreativeLab/template-for-jsar-widget/assets/52097569/a6c30b74-c34c-433e-99b0-78807f9f9cec)

**Comment by yorkie** [comment]
@xuhao8948 你好，可以检查下是否之前安装过 Transmute DevTools，这个是之前老版本的拓展，它使用的 command 是 transmute-devtools.showSceneView，在最新版已经更新为 JSAR DevTools，它使用的 command 是 jsar-devtools 前缀了，可以从 https://marketplace.visualstudio.com/items?itemName=RokidMCreativeLab.vscode-jsar-devtools 这里下载最新版本试试。

**Comment by xuhao8948** [comment]
解决了，安装了最新的拓展就可以了
